server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camel_proxy_db
    username: camel_proxy
    password: 123
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

camel:
  component:
    servlet:
      mapping:
        context-path: /api/report/*

clients:
  client[0]:
    ipAddress: 127.0.0.1
    urlVitakor: localhost:8088/mockBasicHttpBinding_ErWebService
    urlKomtek: p-ovis-psserv-2.hostco.ru:8080/FerIntegration/services/FerIntegration
  client[1]:
    ipAddress: 127.0.0.2
    urlVitakor: localhost:8081/
    urlKomtek: localhost:8082/
  client[2]:
    ipAddress: 127.0.0.3
    urlVitakor: localhost:8083/
    urlKomtek: localhost:8084/

logging:
  level:
    org:
      springframework:
          ws: TRACE