server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camel_db
    username: cameluser
    password: 123
  flyway:
    user: cameluser
    password: 123
    url: jdbc:postgresql://localhost:5432/camel_db
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

camel:
  component:
    servlet:
      mapping:
        context-path: /api/report/*

clients:
  client[0]:
    ipAddress: 127.0.0.1
    urlVitakor: localhost:8088/hi
    urlKomtek: localhost:8089/hi1
  client[1]:
    ipAddress: 127.0.0.2
    urlVitakor: localhost:8081/
    urlKomtek: localhost:8082/
  client[2]:
    ipAddress: 127.0.0.3
    urlVitakor: localhost:8083/
    urlKomtek: localhost:8084/

logging:
  level:
    org:
      springframework:
          ws: TRACE